---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: mywebsite02-scc-storeuser
  labels:
    backstage.io/kubernetes-id: mywebsite02
    app.kubernetes.io/name: mywebsite02
    rht-gitops.com/janus-argocd: mywebsite02
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 10001
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:saturday-test:storeuser-sa
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: mywebsite02-scc-storeuseradmin
  annotations:
    backstage.io/kubernetes-id: mywebsite02
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:saturday-test:storeuseradmin-sa
